# ...
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
#         ↓ プロジェクトにある package.json の @types/node の値と同じにするといいと思います

-         node-version: "16"

+         node-version: "20"

          cache: ${{ steps.detect-package-manager.outputs.manager }}
# ...
      - name: Build with Next.js
        run: ${{ steps.detect-package-manager.outputs.runner }} next build

-     - name: Static HTML export with Next.js

-       run: ${{ steps.detect-package-manager.outputs.runner }} next export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./out
# ...
